### ISSUE TITLE
Onyx.merge does not remove a nested object key

### ISSUE THREAD

**Issue by thienlnam** [Expensify/react-native-onyx#301]
If you set an object key to null, Onyx.merge will remove it 

```
Object: {
	transactionID: 12312312
	comment: {
			waypoints: {
				waypoint0: {}
			}
     }
}
```

This works for first level keys
// Remove all first level keys that are explicitly set to null.
```
Onyx.merge(key, {
	transactionID: null
}
```

Corresponding object: 
```
{
	comment: {
			waypoints: {
				waypoint0: {}
			}
     }
}
```

But if you try to remove a nested key

```
Onyx.merge(key, {
	comment: {
		waypoints: {
			waypoint0: null
		}
	}
}
```

It will just set the value to null
```
{
	comment: {
			waypoints: {
				waypoint0: null
			}
     }
}
```

**Comment by neil-marcellini** [comment]
following

**Comment by tgolen** [comment]
This is very interesting! I didn't believe it at first, but I did a quick test and confirmed exactly what you report. @chrispader you might be interested in checking this one out (our resident expert on `Onyx.merge()` 😁 ).

**Comment by tgolen** [comment]
@thienlnam Could you give a little more context into the underlying thing you're trying to do and why it's preferrable to remove the nested key as opposed to having it remain as `null`?

I could see "consistency" as one argument (and a good one at that), but I kind of feel there needs to be a better reason to change it since it's changing some very low-lying parts of the lib.

**Comment by chrispader** [comment]
Yes this is indeed a bit inconsistent, but until now this was actually the intended output.

I'm open to changing this so all `null` values will be removed when merging

**Comment by neil-marcellini** [comment]
A PR was raised to fix this https://github.com/Expensify/react-native-onyx/pull/350. If top level keys are removed when set to null then we should do the same for nested keys IMO.

**Comment by thienlnam** [comment]
> @thienlnam Could you give a little more context into the underlying thing you're trying to do and why it's preferrable to remove the nested key as opposed to having it remain as null?

Yeah, mostly just an expectation on how merging a null value would work and specifically for waypoints we had the issue because we keyed them like this, and used that to determine the order of the stops / when to add new ones

```
...
{
	waypoint1: {}
    waypoint2: {}
    waypoint3: {}
}
```

It just becomes difficult to determine when to add a new waypoint. So for example, if I remove a waypoint it should be
```
...
{
	waypoint1: {}
    waypoint2: {}
}
```

But since it doesn't null out, it would be
```
...
{
	waypoint1: {}
    waypoint2: {}
    waypoint3: null
}
```

And let's say I wanted to add a new waypoint - I'd have to find the first null waypoint and merge an empty object into it. 

And if I deleted multiple stops, it becomes difficult to keep track of - we'd reorder the waypoints and leave all the empty waypoints as waypointX?
```
...
{
	waypoint1: {}
    waypoint2: null
    waypoint3: {}
	waypoint4: null
	waypoint5: {}
	waypoint6: null
}
```

In that specific scenario I ran into, it would be nice if we could remove unused nested object keys and I'm sure there are a few other cases that cleaning up the data object would be nice

**Comment by chrispader** [comment]
I just created a PR for this [here](https://github.com/Expensify/react-native-onyx/pull/353). Should be done really soon 👍

**Comment by thienlnam** [comment]
Merged!

**Comment by thienlnam** [comment]
PR was reverted

**Comment by thienlnam** [comment]
Yup looks good, thanks!

**Comment by paultsimura** [comment]
Hi folks, while working on my PR, I think I've run into a similar issue again. 

Let's take this test case:
1. There is no existing value of a given key in Onyx;
2. We call `merge` with a nested `null`;

**Should the `null` be ignored here** (since if there was an existing value, the `null` will remove it)?

Unit test for this case:
```js
    it('should merge a non-existing key with a nested null removed', () => {
        let testKeyValue;

        connectionID = Onyx.connect({
            key: ONYX_KEYS.TEST_KEY,
            initWithStoredValues: false,
            callback: (value) => {
                testKeyValue = value;
            },
        });

        return Onyx.merge(ONYX_KEYS.TEST_KEY, {
            waypoints: {
                1: 'Home',
                2: 'Work',
                3: null,
            },
        }).then(() => {
            expect(testKeyValue).toEqual({
                waypoints: {
                    1: 'Home',
                    2: 'Work',
                },
            });
        });
    });
```

The test fails, the persisted value is:
```json
{
  "waypoints": {
    "1": "Home",
    "2": "Work",
    "3": null
  }
}
```

cc: @tgolen @thienlnam

**Comment by paultsimura** [comment]
I've narrowed the issue down a little.

Here's a failing unit test of the `fastMerge` function that I believe shouldn't be failing. Please correct me if I'm wrong:

Given:
https://github.com/Expensify/react-native-onyx/blob/db7007fd67d0e3fc28be5496f38805f825eaf1bf/tests/unit/fastMergeTest.js#L15-L34

This test fails:
```js
    it('should merge an object with an empty object and remove deeply nested null values', () => {
        const result = utils.fastMerge({}, testObjectWithNullishValues);
        expect(result).toEqual(testObjectWithNullValuesRemoved);
    });
```

The actual `result` is:
```json
{
  "b": {
    "c": {
      "h": "h"
    },
    "d": {
      "e": null
    }
  }
}
```

The top-level nullish values are removed (the `a: undefined` was removed, the same happens if I change `undefined` to `null`), but the nested ones are retained.
