### ISSUE TITLE
Nested null is not removed when merging into an empty value

### ISSUE THREAD

**Issue by neil-marcellini** [Expensify/react-native-onyx#508]
## Problem
The problem is described by @paultsimura [here](https://github.com/Expensify/react-native-onyx/issues/301#issuecomment-1987950312).

## Solution
Investigate and fix it.

**Comment by neil-marcellini** [comment]
❗❗ Heads up, I'm going to be OOO working from Spain 🇪🇸 part time until 3/28. Most days I will be working 50%, some days 100%. Please DM me if something needs urgent attention.❗❗

**Comment by chrispader** [comment]
@paultsimura you're completely right, all of these tests (2 Onyx, 1 fastMerge) shouldn't be failing:

https://github.com/Expensify/react-native-onyx/issues/301#issuecomment-1987950312
https://github.com/Expensify/react-native-onyx/issues/301#issuecomment-1988689209

The nested nulls should be removed already at the level of the `fastMerge` function, because the `shouldRemoveNullObjectValues` parameter is `true` by default. I've created a PR to fix, simplify and further document the `fastMerge` implementation: https://github.com/Expensify/react-native-onyx/pull/518

As far as i see it, the changes by @janicduplessis in #411 to *not* remove nested null values in cache don't affect this though.

**Comment by neil-marcellini** [comment]
Great thanks so much @chrispader! Now we just need an App PR to update the Onyx version right? What's the plan for that?

**Comment by chrispader** [comment]
Agree, i think we'll want to wait for #519 and potentially also #515 before we create a bump PR in E/App. Right now, these PRs are only affecting @paultsimura 's work on his PR, if i understand correctly...

**Comment by neil-marcellini** [comment]
Ok then I think we can call this done. Please lmk if it needs to be re-opened for some reason.
